4 add overlay function
alexanderstrigun/gift_idea_app pull request #15
Opened 2021-11-01 14:15 UTC by alexanderstrigun

2021-11-01 14:44 UTC, mpagels requested changes
Hi Alex,

good progress here. I found some things I want to mention:

First, please provide a pull request description with information what was done here.
It helps the reviewer to focus on things that are important in the pull request.

Try to use the present time in your commit messages. Read more about [here](https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/).

Since you're using `styled-components` I would get rid of the `global.css` and use `GlobalStyles` from `styled-components`. Read more about it [here](https://scalablecss.com/styled-components-global-styles/).

Avoid variable names like `test`. Try to find meaningful name for it. Don't be afraid of long names. For example `listOfSelectedCharacters` is total fine and understandable.

Try not to put a `console.log` in production code.

And I would recommend putting all the logic inside the `_app.js` file into to `index.js` file. The `_app.js` is not here to hold that kind of information. Read more about it [here](https://jools.dev/nextjs-_appjs-example).

If you have any questions, please let me know.

2021-11-01 14:44 UTC, mpagels commented on utils/categoryDD.js
> +console.log(categoryDD);
Here is a lonely `console.log`
```suggestion
```

2021-11-01 14:44 UTC, mpagels commented on pages/_app.js
> +    console.log(dropdownInput);
`console.log` here. Recommend removing this.

2021-11-01 14:44 UTC, mpagels commented on components/Dropdown.jsx
> +            console.log(test);
`console.log` here.

2021-11-01 14:44 UTC, mpagels commented on components/Dropdown.jsx
>          >
Not a fan of the inline callback. Would recommend creating a function with the logic before the `return` statement and passing it here.

2021-11-01 14:44 UTC, mpagels commented on components/Dropdown.jsx
> +            {test}
`test`? What does that mean? Try to find meaningful names. When you testing stuff out, then this branch is not ready for merging ;-)

2021-11-01 14:44 UTC, mpagels commented on components/AddOverlay.jsx
> +      <div className={overlayState ? "visibleOverlay" : "invisibleOverlay"}>
Instead of using 
```css
display: none
```
you should use conditional rendering.

```js
visibleOverlay ? <Form /> : ""
```

2021-11-01 14:44 UTC, mpagels commented on components/AddOverlay.jsx
> +            </AddButton>
What is this button doing? You prevent the default behavior. Ok. But then what? Should not add something?

2021-11-02 08:35 UTC, alexanderstrigun commented on components/Dropdown.jsx
> +            {test}
Done, thanks for the hint :)

2021-11-02 10:15 UTC, alexanderstrigun commented on utils/categoryDD.js
> +console.log(categoryDD);
console.log removed

2021-11-02 10:15 UTC, alexanderstrigun commented on pages/_app.js
> +    console.log(dropdownInput);
console.log removed

2021-11-02 10:15 UTC, alexanderstrigun commented on components/Dropdown.jsx
> +            console.log(test);
console.log removed

2021-11-02 10:16 UTC, alexanderstrigun commented on components/Dropdown.jsx
>          >
Added clickhandler functions outside of the returns, wherever applicable. Thanks for the hint!

2021-11-02 10:16 UTC, alexanderstrigun commented on components/AddOverlay.jsx
> +      <div className={overlayState ? "visibleOverlay" : "invisibleOverlay"}>
Done

2021-11-02 10:17 UTC, alexanderstrigun commented on components/AddOverlay.jsx
> +            </AddButton>
This button will have a function within this sprint.

2021-11-02 10:20 UTC, alexanderstrigun commented
comment regarding state definition within the app.js: i would like to keep it as is for the time being. As soon as i properly learned how to use data providers (this or next sprint), i will change this, so that the the app. js is not as cluttered anymore.

2021-11-02 10:20 UTC, merged