9 home card function remove and edit
alexanderstrigun/gift_idea_app pull request #20
Opened 2021-11-05 10:49 UTC by alexanderstrigun

**key achievements**

- individual gift items can now be removed via clicking the delete icon
- individual gift items can no be edited via clicking the edit icon
- in the dropdown component, the custom created dropdown was replaced with a select element

2021-11-05 11:00 UTC, StefanBehring commented on components/AddOverlay.jsx
> +    if (editMode === true) {
```suggestion
    if (editMode) {
```
Does the same

2021-11-05 11:00 UTC, StefanBehring commented on components/AddOverlay.jsx
>                <GrClose></GrClose>
```suggestion
              <GrClose />
```

2021-11-05 14:10 UTC, djfarly requested changes
Hej Alex,

thanks for the PR! Great progress.

I noticed a few things regarding naming as well as function signatures. Maybe we should talk about namings on monday - i think that would be a bit easier than me typing it all out.

Anyway keep going strong! ✌️

2021-11-05 14:10 UTC, djfarly commented on components/Card.jsx
> +    const clickHandlerRemoveGift = () => {
`handleRemoveGift`

2021-11-05 14:10 UTC, djfarly commented on components/Card.jsx
> +      });
This seems redundant. `index` is the second parameter of `giftList.map((individualGift, index) => {`. Here you're doing extra work that just gives you something you already know. `selectedGiftIndex` is the same as `index`.

2021-11-05 14:10 UTC, djfarly commented on components/Card.jsx
> +    const clickHandlerEditGift = () => {
phew - maybe we can talk about naming on monday? I'll stop here - i think you got the gist 😄🥺

2021-11-05 14:10 UTC, djfarly commented on components/Card.jsx
> +      );
Consider using a single object parameter instead of multiple params.

2021-11-05 14:10 UTC, djfarly commented on components/Dropdown.jsx
>    const categoryDDLiItems = categoryDD.map((categoryDDitem) => {
Why is `categoryDD` an array?

2021-11-05 14:10 UTC, djfarly commented on pages/_app.js
> +  console.log(dropdownInput);
Remove console.log

2021-11-05 14:10 UTC, djfarly commented on pages/_app.js
> +    priceInputHandler(selectedGift.price);
I am confused as to what these handlers do…

2021-11-08 16:20 UTC, alexanderstrigun commented
added changes as suggested by jan.

2021-11-08 16:22 UTC, alexanderstrigun commented
removed a console log

2021-11-08 16:24 UTC, alexanderstrigun commented on components/AddOverlay.jsx
>                <GrClose></GrClose>
thx for the hint! :)

2021-11-08 17:57 UTC, djfarly approved these changes
🎊

2021-11-08 17:57 UTC, djfarly commented on server/server.mjs
> +server.listen(8000);
I think you do not need this file.

For all other things: LGTM 😱✌️

2021-11-08 19:01 UTC, alexanderstrigun commented on server/server.mjs
> +server.listen(8000);
cool, thanks!

2021-11-08 19:02 UTC, merged